---
name: JSAN
version: 0.13
author:
  - Ingy döt Net <ingy@cpan.org>
abstract: Wikitext and Wysiwyg editor for Wikis and Blogs
license: lgpl
build_requires:
  Test.Simple: 0.11
provides:
  Wikiwyg:
    file: lib/Wikiwyg.js
    version: 0.13
generated_by: hand
keywords:
  - wysiwyg
  - wiki
  - wikitext
  - blog
  - weblog
