$JS = "<A href=\"";
$JE = "\">";
$TS = "<A name=\"";
$TE = "\">";
$AE = "</A>";
$LI = "<LI>";
$IL = "</LI>";
$UL = "<UL>";
$LU = "</UL>";
$DIV = "<DIV>";
$VID = "</DIV>";
$REFT = "<TABLE cols=1 border=2>";
$TFER = "</TABLE>";
$TR = "<TR>";
$RT = "</TR>";
$TH = "<TH>";
$HT = "</TH>";
$TD = "<TD width=\"10%\">";
$DT = "</TD>";
$ERF = "<FONT color=#ff0000>";
$FRE = "</FONT>";
