#!/usr/bin/perl
# Author: Crawford Currie http://c-dot.co.uk
#
# Generates WebNotify from the WaitingFor and ReportedBy fields
#
my $where = '/home/twiki4/twikisvn/data/Bugs';
my $text = `perl -T ./view topic="Bugs.GenerateWebNotify" -skin text -contenttype text/plain`;
my %topics;
foreach my $line (split(/\r?\n/, $text)) {
    next unless $line =~ s#<a.*>(.*)</a>#$1#g;
    $line =~ s/TWiki:Main.//g;
    if ($line =~ /^(.*):(.*)$/) {
        my ($names, $topic) = ($1, $2);
        foreach my $name (split(/[,;\s]+/, $names)) {
            if ($name =~ /^[A-Z]+[a-z]+[A-Z]/) {
                $topics{$name} = '' unless $topics{$name};
                $topics{$name} .= $topic;
            }
        }
    }
}
if (open(F, "<$where/DontBugMe.txt")) {
    local $/ = "\n";
    while (<F>) {
        $_ =~ s#(TWiki:)?Main[./]##g;
        next unless $_ =~ /^\s*\* ([A-Z]+[a-z]+[A-Z]\w+)\s*$/;
        delete $topics{$1};
    }
    close(F);
}
open(F, ">$where/WebNotify.txt") || die "Can't open WebNotify: $!";
print F <<GUFF;
This topic is automatically generated by a script running on the server. The
script analysis all the 'WaitingFor' and 'ReportedBy' fields in reports and
generates this WebNotify.

You can exclude yourself from all notification by adding yourself to the topic
DontBugMe.
GUFF
foreach my $name (sort keys %topics) {
    print F "   * $name: $topics{$name}\n";
}
close(F);
